name: EconomyAPI
main: onebone\economyapi\EconomyAPI
version: 3.0.1
author: onebone
api:
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 2.0.0
- 2.1.0

permissions:
 economyapi.*:
  default: op
  children:
   economyapi.command.*:
    default: op
    children:
     economyapi.command.setmoney:
      default: op
     economyapi.command.mymoney:
      default: true
     economyapi.command.givemoney:
      default: op
     economyapi.command.pay:
      default: true
     economyapi.command.seemoney:
      default: true
     economyapi.command.topmoney:
      default: true
     economyapi.command.takemoney:
      default: op
